name: deploy-joshr

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tf
        shell: bash
    environment: production
    env:
      ARM_CLIENT_ID: "${{ secrets.CLIENT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.TENANT_ID }}"
      ARM_MSI_ENDPOINT: false
      ARM_USE_MSI: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ./tf

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./tf

      - name: Terraform Apply
        working-directory: ./tf
        run: terraform apply -input=false -auto-approve -no-color -var-file=./env/all/variables.tfvars -var-file=./env/joshr/variables.tfvars